language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pyspark_gateway .

script:
  - docker run -i -e CI=true -t pyspark_gateway python tests/test_pyspark_gateway.py
