language: generic

sudo: required

services:
  - docker

before_install:
  - docker build -t pyspark_gateway_2_7 -f docker/2_7_Dockerfile .
  - docker build -t pyspark_gateway_3_6 -f docker/3_6_Dockerfile .

maxtrix:
  include:
  - name: "Python 2.7"
    env: CONTAINER=pyspark_gateway_2_7
  - name: "Python 3.6"
    env: CONTAINER=pyspark_gateway_3_6

script:
  - docker run -i -e CI=true -t $CONTAINER python tests/test_pyspark_gateway.py
