dist: xenial
language: python

python:
  - '2.7'
  - '3.6'

before_install:
  - sudo apt-get update
  - sudo apt-get install -y wget openjdk-8-jdk-headless
  - wget -q -O scala.deb https://downloads.lightbend.com/scala/2.12.6/scala-2.12.6.deb
  - sudo dpkg -i scala.deb

install:
  - pip install -e .[dev]

script:
  python tests/test_pyspark_gateway.py
