name: Docker Image CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]

jobs:

  python_3_6:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t pyspark_gateway_3_6 -f docker/3_6_Dockerfile .
    - name: Run Tests
      run: docker run -it -e CI=true pyspark_gateway_3_6 python tests/test_pyspark_gateway.py

  python_3_7:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build -t pyspark_gateway_3_7 -f docker/3_7_Dockerfile .
    - name: Run Tests
      run: docker run -it e CI=true pyspark_gateway_3_7 python tests/test_pyspark_gateway.py
